@startuml random_walk_collision_avoidance

left to right direction
hide empty description

state RandomWalk {
    [*] --> GoingStraight
    GoingStraight : go straight
    GoingStraight --> Turning : after 5 seconds

    Turning : turn right
    Turning --> GoingStraight : after 1 second
}
[*] --> RandomWalk
RandomWalk --> Obstacle : found obstacle / stop moving

state Obstacle <<choice>>
Obstacle --> ObstacleRight : [on right]
Obstacle --> ObstacleLeft : [on left]

ObstacleLeft : turn right
ObstacleLeft -u-> RandomWalk : no obstacles left and right / stop turning

ObstacleRight : turn left
ObstacleRight -u-> RandomWalk : no obstacles left and right / stop turning

@enduml