@startuml random_walk_collision_avoidance

left to right direction
hide empty description

[*] --> RandomWalk
RandomWalk --> Obstacle

state Obstacle <<choice>>
Obstacle --> ObstacleRight : [on right]
Obstacle --> ObstacleLeft : [on left]

ObstacleLeft : turn right
ObstacleLeft -u-> RandomWalk : no obstacles left and right

ObstacleRight : turn left
ObstacleRight -u-> RandomWalk : no obstacles left and right

@enduml